[package]
name = "seashell"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.20"
env_logger = "0.11.1"
zbus = "5.11.0"
gtk = { package = "gtk4", version = "0.10.0", features = [ "v4_18" ] }
gtk4-layer-shell = "0.6.3"
dbusmenu-glib = "0.1.0"
